"""Exact floor/ceil of the adjacency spectral radius, in integer/rational arithmetic.

Why this exists.  ``scripts/gen/invariants._spectral_bracket`` computes
``floor(lambda_1)`` correctly (smallest integer k with kI - A positive definite,
by Sylvester on integer principal minors), but decides ``ceil(lambda_1)`` with

    if det(fl*I - A) == 0:  return fl, fl

which tests whether ``fl`` is *an* eigenvalue, not whether it is the *largest*.
On P_5 (graph6 ``Dh_``) the spectrum is {+-sqrt3, +-1, 0}: ``fl = 1`` is an
eigenvalue, so the campaign returns ``ceil(lambda_1) = 1`` where the true value
is 2.  Nineteen of the 12,112 graphs of `D` are affected; ``floor(lambda_1)`` is
unaffected on all of them.

The fix used here, still exact and still integer-only:

    lambda_1 lies in [fl, fl+1) by construction, so ceil(lambda_1) = fl exactly
    when lambda_1 = fl.  For a *connected* graph lambda_1 is a simple eigenvalue
    whose eigenvector is strictly positive (Perron-Frobenius), and no other
    eigenvector can be strictly positive (it would have to be orthogonal to a
    positive vector).  So lambda_1 = fl iff the null space of fl*I - A is
    one-dimensional and generated by a vector with all entries of one sign.

Null spaces are computed by exact Fraction Gaussian elimination.
"""
from __future__ import annotations

from fractions import Fraction
from typing import List, Sequence


def _det_int(M: List[List[int]]) -> int:
    """Exact integer determinant, Bareiss fraction-free elimination."""
    n = len(M)
    if n == 0:
        return 1
    A = [row[:] for row in M]
    sign = 1
    prev = 1
    for k in range(n - 1):
        if A[k][k] == 0:
            piv = None
            for i in range(k + 1, n):
                if A[i][k] != 0:
                    piv = i
                    break
            if piv is None:
                return 0
            A[k], A[piv] = A[piv], A[k]
            sign = -sign
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                A[i][j] = (A[i][j] * A[k][k] - A[i][k] * A[k][j]) // prev
            A[i][k] = 0
        prev = A[k][k]
    return sign * A[n - 1][n - 1]


def _null_space(M: List[List[int]]):
    """Basis of the rational null space of an integer matrix, exact."""
    n = len(M)
    A = [[Fraction(x) for x in row] for row in M]
    piv_col = []
    r = 0
    for c in range(n):
        p = None
        for i in range(r, n):
            if A[i][c] != 0:
                p = i
                break
        if p is None:
            continue
        A[r], A[p] = A[p], A[r]
        inv = A[r][c]
        A[r] = [x / inv for x in A[r]]
        for i in range(n):
            if i != r and A[i][c] != 0:
                f = A[i][c]
                A[i] = [a - f * b for a, b in zip(A[i], A[r])]
        piv_col.append(c)
        r += 1
        if r == n:
            break
    free = [c for c in range(n) if c not in piv_col]
    basis = []
    for fc in free:
        vec = [Fraction(0)] * n
        vec[fc] = Fraction(1)
        for i, pc in enumerate(piv_col):
            vec[pc] = -A[i][fc]
        basis.append(vec)
    return basis


def spectral_bracket(adj: Sequence[int], n: int):
    """(floor(lambda_1), ceil(lambda_1)) exactly, for a connected graph."""
    A = [[1 if adj[i] >> j & 1 else 0 for j in range(n)] for i in range(n)]

    def lt(k: int) -> bool:                        # lambda_1 < k ?
        M = [[(k if i == j else 0) - A[i][j] for j in range(n)] for i in range(n)]
        for s in range(1, n + 1):
            if _det_int([row[:s] for row in M[:s]]) <= 0:
                return False
        return True

    hi = 0
    while hi <= n and not lt(hi + 1):
        hi += 1
    hi += 1                                        # smallest integer k with lambda_1 < k
    fl = hi - 1                                    # lambda_1 in [fl, fl+1)

    M = [[(fl if i == j else 0) - A[i][j] for j in range(n)] for i in range(n)]
    if _det_int(M) != 0:
        return fl, fl + 1                          # fl is not an eigenvalue at all
    ns = _null_space(M)
    if len(ns) != 1:                               # lambda_1 is simple on a connected graph
        return fl, fl + 1
    v = ns[0]
    if all(x > 0 for x in v) or all(x < 0 for x in v):
        return fl, fl                              # Perron vector: fl == lambda_1
    return fl, fl + 1
